version: '3'
services:
  wavelog-main:
    image: jk13xyz/wavelog:dev
    container_name: wavelog-main
    depends_on:
      - wavelog-mariadb
    volumes:
      - wavelog-config:/var/www/html/application/config
      - wavelog-uploads:/var/www/html/uploads
      - wavelog-images:/var/www/html/images
    ports:
      - "7373:80"
    restart: unless-stopped  
    
  wavelog-mariadb:
    image: mariadb:latest
    container_name: wavelog-mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: wavelog
      MARIADB_USER: wavelog
      MARIADB_PASSWORD: "STRONG_PASSWORD"
    volumes:
      - wavelog-dbdata:/var/lib/mysql
    restart: unless-stopped

  wavelog-phpmyadmin:
    image: phpmyadmin:latest
    container_name: wavelog-phpmyadmin
    depends_on:
      - wavelog-mariadb
    environment:
      UPLOAD_LIMIT: 128M
      PMA_HOST: wavelog-mariadb
      PMA_PORT: 3306
      PMA_USER: wavelog
      PMA_PASSWORD: "STRONG_PASSWORD"
    restart: unless-stopped
    ports:
      - "7374:80" 

volumes:
  wavelog-dbdata:
  wavelog-config:
  wavelog-uploads:
  wavelog-images: